-- AlterTable
ALTER TABLE "CAPA" ADD COLUMN "rcaApproved" BOOLEAN;
ALTER TABLE "CAPA" ADD COLUMN "rcaOverrideAt" DATETIME;
ALTER TABLE "CAPA" ADD COLUMN "rcaOverrideBy" TEXT;
ALTER TABLE "CAPA" ADD COLUMN "rcaOverrideById" TEXT;
ALTER TABLE "CAPA" ADD COLUMN "rcaOverrideReason" TEXT;
ALTER TABLE "CAPA" ADD COLUMN "rcaReviewNotes" TEXT;
ALTER TABLE "CAPA" ADD COLUMN "rcaReviewedAt" DATETIME;
ALTER TABLE "CAPA" ADD COLUMN "rcaReviewedBy" TEXT;
ALTER TABLE "CAPA" ADD COLUMN "rcaReviewedById" TEXT;
